### ISSUE TITLE
Error while parsing file

### ISSUE THREAD

**Issue by mrpackethead** [conix-security/springbok#10]
I am not able to parse my fortigate files...  After i import it, it just stops.. In the background this is what i'm seeing.

--------------Zone list-------------------
{}
Traceback (most recent call last):
  File "/home/frazera/springbok/Gtk/Gtk_MenuBar.py", line 454, in on_click
    firewalls = Parser.parser(filename, parser_module, progressBar)
  File "/home/frazera/springbok/Parser/Parser.py", line 70, in parser
    return _parse_kit.get_firewall()
  File "/home/frazera/springbok/Parser/FortiGate/FortiGateYacc.py", line 148, in get_firewall
    end_zones()
  File "/home/frazera/springbok/Parser/FortiGate/FortiGateYacc.py", line 166, in end_zones
    f = open(path + 'zones2', 'w')
IOError: [Errno 2] No such file or directory: '/home/frazera/springbok/Parser/FortiGate/../../output/zones2'

**Comment by Bwajajaja** [comment]
Hey man, I have the same problem as you. I want to import a fortigate conf file but it doesn't work and in the background It appears the same message as you. Were you able to solve it?

**Comment by Bwajajaja** [comment]
> I am not able to parse my fortigate files... After i import it, it just stops.. In the background this is what i'm seeing.
> 
> --------------Zone list-------------------
> {}
> Traceback (most recent call last):
> File "/home/frazera/springbok/Gtk/Gtk_MenuBar.py", line 454, in on_click
> firewalls = Parser.parser(filename, parser_module, progressBar)
> File "/home/frazera/springbok/Parser/Parser.py", line 70, in parser
> return _parse_kit.get_firewall()
> File "/home/frazera/springbok/Parser/FortiGate/FortiGateYacc.py", line 148, in get_firewall
> end_zones()
> File "/home/frazera/springbok/Parser/FortiGate/FortiGateYacc.py", line 166, in end_zones
> f = open(path + 'zones2', 'w')
> IOError: [Errno 2] No such file or directory: '/home/frazera/springbok/Parser/FortiGate/../../output/zones2'

Hey man, I have the same problem as you. I want to import a fortigate conf file but it doesn't work and in the background It appears the same message as you. Were you able to solve it?

**Comment by mazdafunsunn** [comment]
Had same problem with FortiGate. 
Solved by creating output directory manually:
/springbok/output
