### ISSUE TITLE
Can't convert IPtables

### ISSUE THREAD

**Issue by rmeyer137** [conix-security/springbok#6]
I'm receiving the following error when parsing an Iptables firewall.

Traceback (most recent call last):
  File "/root/springbok/Gtk/Gtk_MenuBar.py", line 454, in on_click
    firewalls = Parser.parser(filename, parser_module, progressBar)
  File "/root/springbok/Parser/Parser.py", line 65, in parser
    _parse_kit.finish()
  File "/root/springbok/Parser/IpTables/IpTablesParser.py", line 433, in finish
    input_path_list = my_parser.create_all_path_from_node(input_node)
  File "/root/springbok/Parser/IpTables/IpTablesParser.py", line 280, in create_all_path_from_node
    for idx, component in enumerate(node.data_list):
AttributeError: 'NoneType' object has no attribute 'data_list'

If you can provide me a private email address I can provide the original file for parsing.

**Comment by dwebber** [comment]
Is there any solution to this?  Same issue.

**Comment by rmeyer137** [comment]
No, I didn't get a solution to the issue.
