### ISSUE TITLE
Export audit results in 0 byte file.

### ISSUE THREAD

**Issue by gjahchan** [conix-security/springbok#8]
Traceback (most recent call last):
  File "/home/kali/Downloads/Springbok/springbok/Gtk/Gtk_MenuBar.py", line 692, in on_export
    Gtk_Main.Gtk_Main().notebook.export(filename)
  File "/home/kali/Downloads/Springbok/springbok/Gtk/Gtk_NoteBook.py", line 293, in export
    Gtk_Export.Gtk_Export(filename, self.export_tab[k], k).save()
  File "/home/kali/Downloads/Springbok/springbok/Gtk/Gtk_Export.py", line 45, in save
    self.callback(fd, self.ref)
  File "/home/kali/Downloads/Springbok/springbok/Gtk/Gtk_Export.py", line 81, in export_distributed_detection
    path += elem.to_string()
AttributeError: 'str' object has no attribute 'to_string'

**Comment by DJTacki** [comment]
Same issue here.
