### ISSUE TITLE
Program fails to launch.

### ISSUE THREAD

**Issue by ghost** [conix-security/springbok#9]
Here is the crash log:

```WARNING: There was a problem loading the table file: KeyError('p_ip_src_line_2',)
WARNING: 'p_info' not defined as a function
WARNING: Token 'WS' defined, but not used
WARNING: There is 1 unused token
Generating LALR tables
Traceback (most recent call last):
  File "./springbok.py", line 7, in <module>
    from Gtk import Gtk_Main
  File "/root/Desktop/springbok/Gtk/Gtk_Main.py", line 10, in <module>
    import Gtk_NetworkCanvas
  File "/root/Desktop/springbok/Gtk/Gtk_NetworkCanvas.py", line 14, in <module>
    from matplotlib.backends.backend_gtkagg import FigureCanvasGTKAgg as FigureCanvas
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gtkagg.py", line 14, in <module>
    from matplotlib.backends.backend_gtk import (
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk.py", line 35, in <module>
    from matplotlib.backends.backend_gdk import RendererGDK, FigureCanvasGDK
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gdk.py", line 33, in <module>
    from matplotlib.backends._backend_gdk import pixbuf_get_pixels_array
ImportError: No module named _backend_gdk
```

**Comment by dexion** [comment]
I have another error:
```bash
Traceback (most recent call last):
  File "springbok.py", line 7, in <module>
    from Gtk import Gtk_Main
  File "/media/sf_D_DRIVE/work/springbok/Gtk/Gtk_Main.py", line 9, in <module>
    import Gtk_MenuBar
  File "/media/sf_D_DRIVE/work/springbok/Gtk/Gtk_MenuBar.py", line 15, in <module>
    from Gtk_DialogBox import Gtk_DialogBox
  File "/media/sf_D_DRIVE/work/springbok/Gtk/Gtk_DialogBox.py", line 10, in <module>
    class Gtk_DialogBox:
  File "/media/sf_D_DRIVE/work/springbok/Gtk/Gtk_DialogBox.py", line 12, in Gtk_DialogBox
    def __init__(self, message, gtk_message=gtk.MESSAGE_INFO, gtk_button=gtk.BUTTONS_OK):
AttributeError: 'module' object has no attribute 'MESSAGE_INFO'
```

I think this is problem with overriding `gtk` module because in python console at project folder I got:
```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gtk
>>> gtk.gtk_version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'gtk_version'
```
in any other folder with same python config I got right:
```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gtk
>>> gtk.gtk_version
(2, 24, 30)
```

**Comment by ghost** [comment]
Forward your display with X11. I got it working after generating that error. Works just fine.

**Comment by dexion** [comment]
Problem was in fresh tcl and gtk versions. After downgrade all works again.

**Comment by filvinc** [comment]
@dexion or @MarineSec : I m experiencing issues to run SpringBok (backend_gtk module not found) : Can you please say Ubuntu version you are running?
Downgrad may help to run this 'old' program;
thks

**Comment by filvinc** [comment]
> Problem was in fresh tcl and gtk versions. After downgrade all works again.

I m experiencing issues to run SpringBok (backend_gtk module not found) : can you please say Ubuntu version you are running?
thks

**Comment by filvinc** [comment]
> Here is the crash log:
> 
> ```
> WARNING: 'p_info' not defined as a function
> WARNING: Token 'WS' defined, but not used
> WARNING: There is 1 unused token
> Generating LALR tables
> Traceback (most recent call last):
>   File "./springbok.py", line 7, in <module>
>     from Gtk import Gtk_Main
>   File "/root/Desktop/springbok/Gtk/Gtk_Main.py", line 10, in <module>
>     import Gtk_NetworkCanvas
>   File "/root/Desktop/springbok/Gtk/Gtk_NetworkCanvas.py", line 14, in <module>
>     from matplotlib.backends.backend_gtkagg import FigureCanvasGTKAgg as FigureCanvas
>   File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gtkagg.py", line 14, in <module>
>     from matplotlib.backends.backend_gtk import (
>   File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk.py", line 35, in <module>
>     from matplotlib.backends.backend_gdk import RendererGDK, FigureCanvasGDK
>   File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gdk.py", line 33, in <module>
>     from matplotlib.backends._backend_gdk import pixbuf_get_pixels_array
> ImportError: No module named _backend_gdk
> ```

I m experiencing same issue to run SpringBok : can you please say Ubuntu version you are running?
thks

**Comment by dexion** [comment]
I don't remember exact version, but I downgrade only tcl and gtk to previous major release, not whole system. By the way, I did't found this program useful for me

**Comment by jumpt** [comment]
> > Here is the crash log:
> > ```
> > WARNING: 'p_info' not defined as a function
> > WARNING: Token 'WS' defined, but not used
> > WARNING: There is 1 unused token
> > Generating LALR tables
> > Traceback (most recent call last):
> >   File "./springbok.py", line 7, in <module>
> >     from Gtk import Gtk_Main
> >   File "/root/Desktop/springbok/Gtk/Gtk_Main.py", line 10, in <module>
> >     import Gtk_NetworkCanvas
> >   File "/root/Desktop/springbok/Gtk/Gtk_NetworkCanvas.py", line 14, in <module>
> >     from matplotlib.backends.backend_gtkagg import FigureCanvasGTKAgg as FigureCanvas
> >   File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gtkagg.py", line 14, in <module>
> >     from matplotlib.backends.backend_gtk import (
> >   File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk.py", line 35, in <module>
> >     from matplotlib.backends.backend_gdk import RendererGDK, FigureCanvasGDK
> >   File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gdk.py", line 33, in <module>
> >     from matplotlib.backends._backend_gdk import pixbuf_get_pixels_array
> > ImportError: No module named _backend_gdk
> > ```
> 
> I m experiencing same issue to run SpringBok : can you please say Ubuntu version you are running?
> thks

I'm getting exactly the same error, running on 18.04

**Comment by SamiEljay** [comment]
hello guys,
i m new in security and parsing and i have to install Springbok in kali. i follow the tuto in github but when i want to lauch Springbot i have the following error : 
python: can't open file 'springbok.py': [Errno 2] No such file or directory

please help, thanks
